name: Gary Sheynkman
favicon: null
layout_spectrum: 0.19993
typography_spectrum: 0.16904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3a3a'
    - '#0f0f0f'
    - '#7c7c7c'
    - '#aeaeae'
    - '#dddddd'
  brandStrength: 0.6922838238533586
  lightness: 0.16382345044985414
  saturation: 0.645918995840475
  rhythmicContrast: 0.6593527740333229
purpose: []
